TruncatedNormalCPP: MCQMCIntegration::DigitalNet< uint64_t > Class Template Reference
MCQMCIntegration::DigitalNet< uint64_t > Class Template Reference
Digital Net class for Quasi Mote-Carlo Method.
#include <DigitalNet.h>
Public Types
enum digital_net_id {
NX = 0, SO = 1, OLDSO = 2, NXLW = 3,
SOLW = 4, RANDOM = -1
}
ID of pre-defined Digital Net.
Public Member Functions
DigitalNet (std::istream &is)
constructor from stream.
DigitalNet (const digital_net_id &id, uint32_t s, uint32_t m)
constructor from pre-defined data.
~DigitalNet ()
destructor.
uint64_t getBase (int i, int j) const
get an element of base matrix of generating point set.
double getPoint (int i) const
get a component of a point vector.
const double * getPoint () const
get a point vector.
uint32_t getS () const
get dimension of digital net.
uint32_t getM () const
get F2 dimension of element of digital net.
void showStatus (std::ostream &os)
show internal status.
void scramble ()
scramble base data
void pointInitialize ()
(re-)initialize point.
void nextPoint ()
state transition to next point.
void setSeed (uint64_t seed)
set seed for random number generator for scramble.
double getWAFOM ()
get WAFOM value if exist.
int64_t getTvalue ()
get t-value if exist.
Static Public Member Functions
static const char * getDataPath ()
get a file path for predefined data.
static uint32_t getParameterSize ()
get number of predefined data kinds.
static const std::string getDigitalNetName (uint32_t index)
get a name of pre-defined digital net.
static const std::string getDigitalNetConstruction (uint32_t index)
get explanation of pre-defined digital net.
static uint32_t getSMax ()
get maximum number of pre-defined digital net dimension s.
static uint32_t getSMin ()
get minimum number of pre-defined digital net dimension s.
static uint32_t getMMax ()
get maximum number of pre-defined digital net F2 dimension m.
static uint32_t getMMin ()
get minimum number of pre-defined digital net F2 dimension m.
Detailed Description
template<>
class MCQMCIntegration::DigitalNet< uint64_t >
Digital Net class for Quasi Mote-Carlo Method.
Explicit specialization for 64-bit unsigned integer.
Member Enumeration Documentation
digital_net_id
enum MCQMCIntegration::DigitalNet< uint64_t >::digital_net_id
ID of pre-defined Digital Net.
Enumerator
NX
SO
Niederreiter-Xing point set.
OLDSO
Sobol point set.
NXLW
Old Sobol point set.
SOLW
Niederreiter-Xing point set of Low WAFOM.
RANDOM
Sobol point set of Low WAFOM.
Constructor & Destructor Documentation
DigitalNet() [1/2]
MCQMCIntegration::DigitalNet< uint64_t >::DigitalNet (std::istream & is)
constructor from stream.
FORMAT:
separators are white spaces or newlines.
1st element : 64 fixed.
2nd element : s, dimension of point set.
3rd element : m, F2 dimension of element of point set.
4th - : s * m elements of 64-bit integers.
last but one: WAFOM value, optional.
last : t-value, optional.
Exceptions
runtime_error when can't read from stream.
DigitalNet() [2/2]
MCQMCIntegration::DigitalNet< uint64_t >::DigitalNet (const digital_net_id & id, uint32_t s, uint32_t m)
constructor from pre-defined data.
Parameters
[in] id ID of pre-defined digital net.
[in] s dimension of point set, s should be 4 <= s <= 10.
[in] m F2 dimension of element of point set, m should be 10 <= m <= 18.
~DigitalNet()
MCQMCIntegration::DigitalNet< uint64_t >::~DigitalNet ()
destructor.
Member Function Documentation
getBase()
uint64_t MCQMCIntegration::DigitalNet< uint64_t >::getBase (int i, int j) const inline
get an element of base matrix of generating point set.
Parameters
[in] i row
[in] j column
Returns
an element of base matrix of generating point set.
getDataPath()
static const char* MCQMCIntegration::DigitalNet< uint64_t >::getDataPath () static
get a file path for predefined data.
Returns
a file path for predefined data.
getDigitalNetConstruction()
static const std::string MCQMCIntegration::DigitalNet< uint64_t >::getDigitalNetConstruction (uint32_t index) static
get explanation of pre-defined digital net.
Returns
explanation of pre-defined digital net.
getDigitalNetName()
static const std::string MCQMCIntegration::DigitalNet< uint64_t >::getDigitalNetName (uint32_t index) static
get a name of pre-defined digital net.
Returns
a name of pre-defined digital net.
getM()
uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getM () const inline
get F2 dimension of element of digital net.
Returns
F2 dimension of element of digital net.
getMMax()
static uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getMMax () static
get maximum number of pre-defined digital net F2 dimension m.
Returns
maximum number of pre-defined digital net F2 dimension m.
getMMin()
static uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getMMin () static
get minimum number of pre-defined digital net F2 dimension m.
Returns
minimum number of pre-defined digital net F2 dimension m.
getParameterSize()
static uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getParameterSize () static
get number of predefined data kinds.
Returns
number of predefined data kinds.
getPoint() [1/2]
double MCQMCIntegration::DigitalNet< uint64_t >::getPoint (int i) const inline
get a component of a point vector.
Parameters
[in] i get i-th component.
Returns
a component of a point vector.
getPoint() [2/2]
const double* MCQMCIntegration::DigitalNet< uint64_t >::getPoint () const inline
get a point vector.
Returns
a point vector.
getS()
uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getS () const inline
get dimension of digital net.
Returns
dimension of digital net.
getSMax()
static uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getSMax () static
get maximum number of pre-defined digital net dimension s.
Returns
maximum number of pre-defined digital net dimension s.
getSMin()
static uint32_t MCQMCIntegration::DigitalNet< uint64_t >::getSMin () static
get minimum number of pre-defined digital net dimension s.
Returns
minimum number of pre-defined digital net dimension s.
getTvalue()
int64_t MCQMCIntegration::DigitalNet< uint64_t >::getTvalue () inline
get t-value if exist.
Returns
t-value
References MCQMCIntegration::DigitalNet< T >::getDataPath(), MCQMCIntegration::DigitalNet< T >::getDigitalNetConstruction(), MCQMCIntegration::DigitalNet< T >::getDigitalNetName(), MCQMCIntegration::DigitalNet< T >::getMMax(), MCQMCIntegration::DigitalNet< T >::getMMin(), MCQMCIntegration::DigitalNet< T >::getParameterSize(), MCQMCIntegration::DigitalNet< T >::getSMax(), and MCQMCIntegration::DigitalNet< T >::getSMin().
getWAFOM()
double MCQMCIntegration::DigitalNet< uint64_t >::getWAFOM () inline
get WAFOM value if exist.
Returns
WAFOM value.
nextPoint()
void MCQMCIntegration::DigitalNet< uint64_t >::nextPoint ()
state transition to next point.
pointInitialize()
void MCQMCIntegration::DigitalNet< uint64_t >::pointInitialize ()
(re-)initialize point.
scramble()
void MCQMCIntegration::DigitalNet< uint64_t >::scramble ()
scramble base data
setSeed()
void MCQMCIntegration::DigitalNet< uint64_t >::setSeed (uint64_t seed)
set seed for random number generator for scramble.
showStatus()
void MCQMCIntegration::DigitalNet< uint64_t >::showStatus (std::ostream & os)
show internal status.
Parameters
[in,out] os output stream
The documentation for this class was generated from the following file:
DigitalNet.h