TruncatedNormalCPP: MCQMCIntegration Namespace Reference
MCQMCIntegration Namespace Reference
Data Structures
class BotevAlgorithm
a class to compute Multivariate Normal Distribution.
class DigitalNet
Digital Net class for Quasi Mote-Carlo Method.
class DigitalNet< uint64_t >
Digital Net class for Quasi Mote-Carlo Method.
struct MCQMCResult
Result Structure of Numeric Integration.
class OnlineVariance
struct TruncatedNormalResult
structure of the result of truncatedNormal.
Functions
template<typename I , typename R , typename D >
MCQMCResult monte_carlo_integration (uint32_t s, uint32_t m, uint32_t N, I &integrand, R &rand, D &dist, int probability=99)
template<typename I , typename D >
MCQMCResult quasi_monte_carlo_integration (uint32_t N, I &integrand, D &digitalNet, int probability=99)
TruncatedNormalResult truncatedNormal (const std::vector< double > &lower, const std::vector< double > &upper, const std::vector< std::vector< double > > &sigma, uint64_t number, DigitalNet< uint64_t > &dn, double probability)
compute Multivariate Normal Distribution by Quasi Monte-Carlo method.
TruncatedNormalResult truncatedNormal (const std::vector< double > &lower, const std::vector< double > &upper, const std::vector< std::vector< double > > &sigma, uint64_t number, DigitalNet< uint64_t >::digital_net_id dnid, uint32_t m, double probability)
compute Multivariate Normal Distribution by Quasi Monte-Carlo method.
TruncatedNormalResult truncatedNormalMC (const std::vector< double > &lower, const std::vector< double > &upper, const std::vector< std::vector< double > > &sigma, uint32_t trialNumber, uint32_t sampleNumber, double probability)
compute Multivariate Normal Distribution by Monte-Carlo method.
Function Documentation
monte_carlo_integration()
template<typename I , typename R , typename D > MCQMCResult MCQMCIntegration::monte_carlo_integration (uint32_t s, uint32_t m, uint32_t N, I & integrand, R & rand, D & dist, int probability = 99)
References MCQMCIntegration::OnlineVariance::absErr(), MCQMCIntegration::OnlineVariance::addData(), and MCQMCIntegration::OnlineVariance::getMean().
quasi_monte_carlo_integration()
template<typename I , typename D > MCQMCResult MCQMCIntegration::quasi_monte_carlo_integration (uint32_t N, I & integrand, D & digitalNet, int probability = 99)
References MCQMCIntegration::OnlineVariance::absErr(), MCQMCIntegration::OnlineVariance::addData(), and MCQMCIntegration::OnlineVariance::getMean().
truncatedNormal() [1/2]
TruncatedNormalResult MCQMCIntegration::truncatedNormal (const std::vector< double > & lower, const std::vector< double > & upper, const std::vector< std::vector< double > > & sigma, uint64_t number, DigitalNet< uint64_t > & dn, double probability)
compute Multivariate Normal Distribution by Quasi Monte-Carlo method.
computes an estimator and a deterministic upper bound of the probability P r(lower < X < upper), where X is a zero-mean multivariate normal vector with covariance matrix Σ, that is, X is drawn from N(0, Σ) infinite values for vectors upper and lower are accepted.
Note
parameter dn, digital net should have dimension s = lower.size - 1. And s should be an integer 4 <= s <= 10, therefore, lower.size size should be 5 <= size <= 11. Moreover, The F2-dimension of element of digitalnet, m should be 10 <= m <= 18.
probability should be one of {0.95, 0.99, 0.999, 0.9999}
Parameters
[in] lower lower truncation limit.
[in] upper upper truncation limit.
[in] sigma covariance matrix of N(0, Σ)
[in] number Monte Carlo simulation effort — the larger the n, the smaller the relative error of the estimator.
[in,out] dn digital net.
[in] probability expected probability such that the result is in the range [p-σ, p+σ].
Returns
estimated value of probability and other information.
truncatedNormal() [2/2]
TruncatedNormalResult MCQMCIntegration::truncatedNormal (const std::vector< double > & lower, const std::vector< double > & upper, const std::vector< std::vector< double > > & sigma, uint64_t number, DigitalNet< uint64_t >::digital_net_id dnid, uint32_t m, double probability)
compute Multivariate Normal Distribution by Quasi Monte-Carlo method.
computes an estimator and a deterministic upper bound of the probability P r(lower < X < upper), where X is a zero-mean multivariate normal vector with covariance matrix Σ, that is, X is drawn from N(0, Σ) infinite values for vectors upper and lower are accepted.
dnid is one of
DigitalNet::digital_net_id::NXLW
DigitalNet::digital_net_id::SOLW Sobol Low WAFOM
Note
The F2-dimension of element of digitalnet, m should be 10 <= m <= 18.
probability should be one of {0.95, 0.99, 0.999, 0.9999}
Parameters
[in] lower lower truncation limit.
[in] upper upper truncation limit.
[in] sigma covariance matrix of N(0, Σ)
[in] number Monte Carlo simulation effort — the larger the number, the smaller the relative error of the estimator.
[in] dnid digital netid.
[in] m F2 dimension of element of digital net.
[in] probability expected probability such that the result is in the range [p - absoluteError, p + absoluteError].
Returns
estimated value of probability and other information.
truncatedNormalMC()
TruncatedNormalResult MCQMCIntegration::truncatedNormalMC (const std::vector< double > & lower, const std::vector< double > & upper, const std::vector< std::vector< double > > & sigma, uint32_t trialNumber, uint32_t sampleNumber, double probability)
compute Multivariate Normal Distribution by Monte-Carlo method.
computes an estimator and a deterministic upper bound of the probability P r(lower < X < upper), where X is a zero-mean multivariate normal vector with covariance matrix Σ, that is, X is drawn from N(0, Σ) infinite values for vectors upper and lower are accepted; Monte Carlo method uses sample size number;
dnid is one of
DigitalNet::digital_net_id::NXLW
DigitalNet::digital_net_id::SOLW Sobol Low WAFOM
DigitalNet::digital_net_id::RANDOM Monte-Carlo method
probability should be one of {0.95, 0.99, 0.999, 0.9999}
Parameters
[in] lower lower truncation limit.
[in] upper upper truncation limit.
[in] sigma covariance matrix of N(0, Σ)
[in] trialNumber Monte Carlo simulation effort — the larger the number, the smaller the relative error of the estimator.
[in] sampleNumber sample number per a trial.
[in] probability expected probability such that the result is in the range [p - absoluteError, p + absoluteError].
Returns
estimated value of probability and other information.