TruncatedNormalCPP: MCQMCIntegration::DigitalNet< T > Class Template Reference
MCQMCIntegration::DigitalNet< T > Class Template Reference
Digital Net class for Quasi Mote-Carlo Method.
#include <DigitalNet.h>
Static Public Member Functions
static const char * getDataPath ()
static uint32_t getParameterSize ()
static const std::string getDigitalNetName (uint32_t index)
static const std::string getDigitalNetConstruction (uint32_t index)
static uint32_t getSMax ()
static uint32_t getSMin ()
static uint32_t getMMax ()
static uint32_t getMMin ()
Detailed Description
template<typename T>
class MCQMCIntegration::DigitalNet< T >
Digital Net class for Quasi Mote-Carlo Method.
This class is almost dummy.
Template Parameters
T uint32_t of uint64_t, currently uint64_t is specialized.
Member Function Documentation
getDataPath()
template<typename T > static const char* MCQMCIntegration::DigitalNet< T >::getDataPath () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getDigitalNetConstruction()
template<typename T > static const std::string MCQMCIntegration::DigitalNet< T >::getDigitalNetConstruction (uint32_t index) static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getDigitalNetName()
template<typename T > static const std::string MCQMCIntegration::DigitalNet< T >::getDigitalNetName (uint32_t index) static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getMMax()
template<typename T > static uint32_t MCQMCIntegration::DigitalNet< T >::getMMax () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getMMin()
template<typename T > static uint32_t MCQMCIntegration::DigitalNet< T >::getMMin () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getParameterSize()
template<typename T > static uint32_t MCQMCIntegration::DigitalNet< T >::getParameterSize () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getSMax()
template<typename T > static uint32_t MCQMCIntegration::DigitalNet< T >::getSMax () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
getSMin()
template<typename T > static uint32_t MCQMCIntegration::DigitalNet< T >::getSMin () static
Referenced by MCQMCIntegration::DigitalNet< uint64_t >::getTvalue().
The documentation for this class was generated from the following file:
DigitalNet.h