TruncatedNormalCPP: MCQMCIntegration::OnlineVariance Class Reference
MCQMCIntegration::OnlineVariance Class Reference
#include <MCQMCIntegration.h>
Public Member Functions
OnlineVariance ()
void addData (const double x)
double getMean () const
double unbiasedVar () const
double var () const
double absErr (const int prob) const
double relErr (const int prob) const
Constructor & Destructor Documentation
OnlineVariance()
MCQMCIntegration::OnlineVariance::OnlineVariance ()
Member Function Documentation
absErr()
double MCQMCIntegration::OnlineVariance::absErr (const int prob) const
Referenced by addData(), MCQMCIntegration::monte_carlo_integration(), and MCQMCIntegration::quasi_monte_carlo_integration().
addData()
void MCQMCIntegration::OnlineVariance::addData (const double x) inline
References absErr(), getMean(), relErr(), unbiasedVar(), and var().
Referenced by MCQMCIntegration::monte_carlo_integration(), and MCQMCIntegration::quasi_monte_carlo_integration().
getMean()
double MCQMCIntegration::OnlineVariance::getMean () const
Referenced by addData(), MCQMCIntegration::monte_carlo_integration(), and MCQMCIntegration::quasi_monte_carlo_integration().
relErr()
double MCQMCIntegration::OnlineVariance::relErr (const int prob) const
Referenced by addData().
unbiasedVar()
double MCQMCIntegration::OnlineVariance::unbiasedVar () const
Referenced by addData().
var()
double MCQMCIntegration::OnlineVariance::var () const
Referenced by addData().
The documentation for this class was generated from the following file:
MCQMCIntegration.h